modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/percivalalb/MapMakingTools/issues"
displayURL="https://minecraft.curseforge.com/projects/map-making-tools/"
logoFile="mmt_logo.png"
[[mods]] #mandatory
    modId="mapmakingtools"
    version="${file.jarVersion}"
    updateJSONURL="https://raw.githubusercontent.com/percivalalb/MapMakingTools/master/version.json"
    displayName="Map Making Tools"
    credits="percivalalb"
    authors="percivalalb"
    description='''
    Map Making Tools
    '''
[[dependencies.doggytalents]] #optional
    modId="forge"
    mandatory=true
    versionRange="[28.1.0,)" #mandatory
    ordering="NONE"
    side="BOTH"