modLoader="javafml"
loaderVersion="[25,)"
issueTrackerURL="https://github.com/percivalalb/MapMakingTools/issues"
displayURL="https://minecraft.curseforge.com/projects/map-making-tools/"
logoFile="mmt_logo.png"

[[mods]] #mandatory
	modId="mapmakingtools"
	version="${file.jarVersion}"
	updateJSONURL="https://raw.githubusercontent.com/percivalalb/MapMakingTools/master/version.json"
	displayName="Map Making Tools"
	credits="Authored By ProPercivalalb"
	authors="ProPercivalalb"
	description='''
    Very useful for making custom adventure maps.
    '''